### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/ic6-checkout#1]
This issue is intended to highlight differnt sections of code that we may find useful for IC6.  I will update this as I get time.

**Comment by hexfusion** [comment]
[Site/Checkout/Validate.pm](https://github.com/sbatschelet/ic6-checkout/blob/master/Site/Checkout/Validate.pm).

This is an interesting concept of doing the validation within IC6 vs relying on external modules.  We could allow for local overload to customize but I really like this and we can easilly work it into proper flute errors.

**Comment by racke** [comment]
Well that is basically copy & waste from IC5.

**Comment by racke** [comment]
There is nothing wrong with external modules IMHO.
Especially if we write them :-).

**Comment by hexfusion** [comment]
True or just have flute do the validation directly woud be sweet.  validate="zip" :+1:

**Comment by racke** [comment]
Yeah that could be done too + we can add JS support for these checks like showing immediately whether value is valid or not.

**Comment by hexfusion** [comment]
yes perfect imo
